version: '2.2'
services:

  php:
    container_name: php_webserver
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: 'php'
      args:
        - PHP_BASE_IMAGE_VERSION
        - X_LEGACY_GD_LIB
        - PECL_XDEBUG_INSTALL_SUFFIX
        - PECL_MONGODB_INSTALL_SUFFIX
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
    links:
      - database
    volumes:
      - ${PWD}/tests:/tests:delegated
      - ${PWD}/app:/app:delegated
      - ${PWD}/logs/apache2:/var/log/apache2:delegated
      - ${PWD}/config/php:/usr/local/etc/php 
      - ${PWD}/config/vhosts:/etc/apache2/sites-enabled
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
  database:
    container_name: mariadb_server
    image: "mariadb:${MARIADB_VERSION}"
    restart: 'always'
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ${PWD}/data/mysql:/var/lib/mysql:delegated
      - ${PWD}/logs/mysql:/var/log/mysql:delegated
      - ${PWD}/config/mariadb/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

